config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'

  devise_for :admins, controllers: { registrations: "admins/registrations",  sessions: 'admins/sessions' }
  devise_for :users, :controllers => { registrations: "users/registrations", sessions: 'users/sessions' }
  devise_for :sellers, :controllers => { registrations: "sellers/registrations", sessions: 'sellers/sessions' }
  
  get '/busca' => 'pages#search'
  post '/busca' => 'pages#search'
  post '/zipcode' => 'pages#zipcode'
  post '/pedir' => 'pages#create'
  get '/login' => 'pages#login'
  get '/login-vendedor' => 'pages#login_sellers'
  get '/cadastro-vendedor' => 'pages#register_seller'

  get '/painel/pedidos' => 'sellers#orders'
  get '/painel/financeiro' => 'sellers#finances'
  get '/painel/locais' => 'sellers#index'
  get '/painel/dados' => 'sellers#edit'
  get '/painel' => 'sellers#index'
  get '/painel/invoice/:id' => 'sellers#view_invoice'
  get '/painel/entrega/:id' => 'sellers#view_delivery'
  get '/painel/entregar/:id' => 'sellers#deliver'
  get '/painel/entregado/:id' => 'sellers#delivered'
  get '/painel/cancelar/:id' => 'sellers#cancel'
  

  get '/admin' => 'admins#index'
  get '/admin/new' => 'admins#new'
  get '/admin/edit' => 'admins#edit'
  get '/admin/admins' => 'admins#admins'
  get '/admin/admins/apagar/:id' => 'admins#destroy_admin'
  get '/admin/clientes' => 'admins#users'
  get '/admin/clientes/:id' => 'admins#view_user'
  get '/admin/clientes/apagar/:id' => 'admins#destroy_user'
  get '/admin/vendedores' => 'admins#sellers'
  get '/admin/vendedores/:id' => 'admins#view_seller'
  get '/admin/pedidos' => 'admins#orders'
  get '/admin/pedidos/apagar/:id' => 'admins#destroy_order'
  get '/pedidos' => 'pages#orders'

end

app/views/pages/create.html.erb
<%= @object.id %>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="HomeGás">
		<title>HomeGás - Entrega de gás em casa</title>
		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700)">
		<!-- Bootstrap core CSS -->
		<link href="/assets/bootstrap.min.css" rel="stylesheet">
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<link href="/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
		<!-- Custom styles for this template -->
		<link href="/assets/site.css" rel="stylesheet">
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="site-wrapper">
			<div class="site-wrapper-inner">
				<div class="cover-container"  style="width:85%;">
					<div class="masthead clearfix"  style="width:85%;">
						<div class="inner"><img class="logo" src="assets/logo-homegas.png">
							<nav>
								<ul class="nav masthead-nav">
									<li><a href="/">INÍCIO</a></li>
									<li><a href="#">Como Funciona</a></li>
									<li><a href="/cadastro-vendedor">Vendedores</a></li>
									<li><a href="#">Contato</a></li>
									<% if user_signed_in? %>
									<li><a href="/pedidos" class="login">Pedidos</a></li>
									<% end %>
									<% if admin_signed_in? %>
									<li><a href="/admin" class="login">Admin</a></li>
									<% end %>
									<% if seller_signed_in? %>
									<li><a href="/painel" class="login">Painel</a></li>
									<% end %>
									<% if !user_signed_in? && !admin_signed_in? && !seller_signed_in? %>
									<li><a href="/login" class="login">Login</a></li>
									<% end %>
								</ul>
							</nav>
						</div>
					</div>
					<div class="inner cover">
						<h1 class="cover-heading">ENTREGA DE GÁS</h1>
						<h4 class="cover-heading">Peça gratuitamente e receba de forma rápida em casa.</h4>
						<div class="row">
							<div class="col-md-5 col-sm-12">
								<%= form_tag("/busca") do %>
								<div class="input-group input-group-lg cover-heading">
									
									<input name="zipcode" class="form-control" placeholder="Seu CEP..." type="text">
									<span class="input-group-btn">
										<button class="btn btn-primary" type="submit">Pedir agora >></button>
									</span>
									
								</div>
								<% end %>
							</div>
							<div class="col-md-7">
							</div>
						</div>
						
					</div>
					<div class="mastfoot">
						<div class="inner">Presente em mais de 30 cidades! Apenas vendedores confiáveis!</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
		<script src="../../dist/js/bootstrap.min.js"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
	</body>
</html>

app/views/pages/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="HomeGás">
    <title>Login - HomeGás</title>
    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/search.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><img height="100%" src="/assets/logo-homegas.png"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/">VOLTAR</a></li>
        </ul>
        </div><!--/.nav-collapse -->
      </nav>
      <div class="container" style="margin-top: 60px;">
        <%= form_for(:user, url: session_path(:user), :html => {:class => 'form-signin'}) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Senha' %>
        </div>
        <div class="form-group">
          <%= f.check_box :'remember_me' %>
          <%= f.label 'Lembrar-me' %>
        </div>
        <%= f.submit "Entrar", class: 'btn btn-lg btn-primary btn-block' %>
        <a href="/login-vendedor" class="btn btn-lg btn-danger btn-block">Sou vendedor</a>
        <% end %>
      </div>
    </body>
  </html>

app/views/pages/login_sellers.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="HomeGás">
    <title>Login - HomeGás</title>
    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/search.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><img height="100%" src="/assets/logo-homegas.png"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/">VOLTAR</a></li>
        </ul>
        </div><!--/.nav-collapse -->
      </nav>
      <div class="container" style="margin-top: 60px;">
        <%= form_for(:seller, url: session_path(:seller), :html => {:class => 'form-signin'}) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Senha' %>
        </div>
        <div class="form-group">
          <%= f.check_box :'remember_me' %>
          <%= f.label 'Lembrar-me' %>
        </div>
        <%= f.submit "Entrar", class: 'btn btn-lg btn-primary btn-block' %>
        <% end %>
      </div>
    </body>
  </html>

app/views/pages/orders.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Pedidos - HomeGás</title>
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/search.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><img height="100%" src="/assets/logo-homegas.png"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/pedidos">Pedidos</a></li>
          <li><a href="/dados">Dados</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/users/sign_out">Sair</a></li>
        </ul>
        </div><!--/.nav-collapse -->
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-md-12">
              <h3>Olá, <%= current_user.name %>!</h3>
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Ordem</th>
                        <th>Empresa</th>
                        <th>Vendedor</th>
                        <th>Data</th>
                        <th>Valor</th>
                        <th>Meio de Pagamento</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @orders.each do |order| %>
                      <tr>
                        <td><a href="">#<%= order.id %></a></td>
                        <td><%= order.firm %></td>
                        <td><%= order.seller_name %></td>
                        <td><%= order.created_at %></td>
                        <td><%= order.value %></td>
                        <td><%= get_payment_label(order.payment) %></td>
                        <td><%= get_status_label(order.status) %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
              <!--/col-span-6-->
            </div>
          </div>
        </div>
      </div>
      
      <script src="/assets/jquery.min.js"></script>
      <script src="/assets/bootstrap.min.js"></script>
      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="/assets/ie10-viewport-bug-workaround.js"></script>
    </body>
  </html>

app/views/pages/register_seller.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Signin Template for Bootstrap</title>
    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/search.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tag %>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><img height="100%" src="/assets/logo-homegas.png"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/">VOLTAR</a></li>
        </ul>
        </div><!--/.nav-collapse -->
      </nav>
      <div class="container" style="margin-top: 60px;">
        <%= form_for(:seller, url: registration_path(:seller), :html => {:class => 'form-signin'}) do |f| %>
        <div class="form-group">
          <%= f.text_field :firm, class: 'form-control', placeholder: 'Empresa' %>
        </div>
        <div class="form-group">
          <%= f.text_field :cnjp, class: 'form-control cnpfj', placeholder: 'CNPJ' %>
        </div>
        <div class="form-group">
          <%= f.text_field :zip_code, class: 'form-control zipcode', placeholder: 'CEP' %>
        </div>
        <div class="form-group">
          <%= f.text_field :city, class: 'form-control city_field', placeholder: 'Cidade' %>
        </div>
        <div class="form-group">
          <%= f.text_field :state, class: 'form-control state_field', placeholder: 'Estado' %>
        </div>
        <div class="form-group">
          <%= f.text_field :neighborhood, class: 'form-control neighborhood_field', placeholder: 'Bairro' %>
        </div>
        <div class="form-group">
          <%= f.text_field :address, class: 'form-control address_field', placeholder: 'Endereço' %>
        </div>
        <div class="form-group">
          <%= f.text_field :distributor, class: 'form-control', placeholder: 'Distribuidora' %>
        </div>
        <div class="form-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Nome do responsável' %>
        </div>
        <div class="form-group">
          <%= f.text_field :cellphone, class: 'form-control', placeholder: 'Telefone' %>
        </div>
        <div class="form-group">
          <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Senha' %>
          <% if @validatable %>
          <span class="help-block"><%= @minimum_password_length %> characters minimum</span>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: 'Confirmação de Senha' %>
        </div>
        <%= f.submit "Cadastrar", class: 'btn btn-lg btn-primary btn-block' %>
        <% end %>
        </div>
        <!-- /container -->
        <script src="https://code.jquery.com/jquery.min.js"></script>
        <script src="/assets/jquery.mask.min.js"></script>
        <script src="/assets/bootstrap.min.js"></script>
        <script src="/assets/site.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="/assets/ie10-viewport-bug-workaround.js"></script>
      </body>
    </html>

app/views/pages/search.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Buscar Vendedor</title>
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/search.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/">VOLTAR</a></li>
        </ul>
        </div><!--/.nav-collapse -->
      </nav>
      <div class="row" style="margin:0; padding-top: 50px;">
        <div class="col-sm-12 col-md-6" style="padding-top: 10px;">
          <form class="new_user" id="new_user" action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="ScMo9sbicgDDlS6crKgv2/aXXYAWV9T/lwXOItvtnzKPkUDR9bd6KmWR/jgUs+RCPDtOgS/CdZ+qiVs+w/6U6g==">
          
          <div class="form-group">
            <label for="user_name">VENDEDOR</label>
            <p class="form-control-static"><%= @sellers.name %></p>
          </div>
          <div class="form-group">
            <label for="user_email">DISTRIBUIDOR</label>
            <p class="form-control-static"><%= @sellers.distributor %></p>
          </div>
          <div class="form-group">
            <label for="user_password">PREÇO</label>
            <p class="form-control-static text-success">R$ 62,00</p>
            <span class="help-block"><small>impostos incluídos</small></span>
          </div><div class="form-group">
          <label for="user_password">TEMPO DE ENTREGA</label>
          <p class="form-control-static">15 minutos</p>
          
        </div>
        <% if !user_signed_in? %>
        <div class="form-group">
          <label for="user_password">FORMAS DE PAGAMENTO</label>
          <p class="form-control-static"><span class="label label-info">CARTÃO </span> <span class="label label-success">DINHEIRO</span></p>
          
        </div>
        <% end %>
        <% if user_signed_in? %>
        <%= form_tag("/pedir") do %>
        
        
        <div class="form-group">
          <label for="user_password">PAGAR COM</label>
          <select class="form-control" name="payment">
            <option value="0">DINHEIRO</option>
            <option value="1">CARTÃO</option>
          </select>
        </div>
        
        <div class="form-group">
          <label for="user_password">INFORMAÇÕES ADICIONAIS</label>
          <textarea class="form-control" name="information" rows="3" placeholder="Deseja adicionar alguma informação para o vendedor?"></textarea>
          
        </div>
        <input type="hidden" name="seller_id" value="<%= @sellers.id %>">
      <button type="submit" id="order" class="btn btn-primary test">CONFIRMAR >> </a>
      <% end %>
      
      <% else %>
      <hr>
      <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modal-login">LOGIN</a> <a href="#" class="btn btn-success" data-toggle="modal" data-target="#modal-register">CRIAR CONTA</a>
      <% end %>
    </form>
  </div>
  <div class="col-md-6" style="padding:0;">
    <iframe id="map_main" width="100%" height="600" frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/directions?origin=<%= @sellers.address+' '+@sellers.neighborhood%>&destination=<%= @location[:address]+' '+@location[:neighborhood]%>&key=<%= get_maps_api %>" allowfullscreen></iframe>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modal-login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
        
        <%= link_to "Esqueçeu a senha?", new_password_path(:user) %>
        
      </div>
      <div class="modal-footer">
        <%= f.submit 'LOGIN', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-register" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Criar Conta</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:user, url: registration_path(:user)) do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Nome' %>
        </div>
        <div class="form-group">
          <%= f.text_field :cpf, class: 'form-control cnpfj', placeholder: 'CPF' %>
        </div>
        <div class="form-group">
          <%= f.text_field :zipcode, class: 'form-control zipcode', placeholder: 'CEP' %>
        </div>
        <div class="form-group">
          <%= f.text_field :city, class: 'form-control city_field', placeholder: 'Cidade' %>
        </div>
        <div class="form-group">
          <%= f.text_field :state, class: 'form-control state_field', placeholder: 'Estado'  %>
        </div>
        <div class="form-group">
          <%= f.text_field :neighborhood, class: 'form-control neighborhood_field', placeholder: 'Bairro' %>
        </div>
        <div class="form-group">
          <%= f.text_field :cpf, class: 'form-control address_field', placeholder: 'Endereço' %>
        </div>
        <div class="form-group">
          <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Senha' %>
          <% if @validatable %>
          <span class="help-block"><%= @minimum_password_length %> characters minimum</span>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: 'Confirmação de senha' %>
        </div>
        
        
      </div>
      <div class="modal-footer">
        <%= f.submit "CRIAR CONTA", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<script src="/assets/jquery.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/site.js"></script>
<script src="/assets/jquery.mask.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/assets/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/pages/user_edit.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="panel">
			<div class="panel-heading">
			<h5>Pedidos Recebidos</h5></div>
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Ordem</th>
							<th>Cliente</th>
							<th>Vendedor</th>
							<th>Data</th>
							<th>Valor</th>
							<th>Meio de Pagamento</th>
							<th>Status</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @orders.each do |order| %>
						<tr>
							<td><a href="#">#<%= order.id %></a></td>
							<td><%= order.seller %></td>
							<td><%= order.seller %></td>
							<td><%= order.created_at %></td>
							<td>R$ <%= order.value %></td>
							<td>
								<% if order.status == 0 %>
								<span class="label label-success">DINHEIRO</span>
								<% else %>
								<span class="label label-info">CARTÃO</span>
							<% end %></td>
							<td>
								<% if order.status == 0 %>
								<span class="label label-warning">PENDENTE</span>
								<% elsif order.status == 1 %>
								<span class="label label-success">EM ENTREGA</span>
								<% elsif order.status == 2 %>
								<span class="label label-info">ENTREGUE</span>
								<% elsif order.status == 3 %>
								<span class="label label-success">CANCELADO</span>
								<% else %>
								<span class="label label-primary">NO IDENT</span>
							<% end %></td>
							<td><a href="#" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-pencil"></i></a></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>