config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'

  devise_for :admins, controllers: { registrations: "admins/registrations",  sessions: 'admins/sessions' }
  devise_for :users, :controllers => { registrations: "users/registrations", sessions: 'users/sessions' }
  devise_for :sellers, :controllers => { registrations: "sellers/registrations", sessions: 'sellers/sessions' }
  
  get '/busca' => 'pages#search'
  post '/busca' => 'pages#search'
  post '/zipcode' => 'pages#zipcode'
  post '/pedir' => 'pages#create'
  get '/login' => 'pages#login'
  get '/login-vendedor' => 'pages#login_sellers'
  get '/cadastro-vendedor' => 'pages#register_seller'

  get '/painel/pedidos' => 'sellers#orders'
  get '/painel/financeiro' => 'sellers#finances'
  get '/painel/locais' => 'sellers#index'
  get '/painel/dados' => 'sellers#edit'
  get '/painel' => 'sellers#index'
  get '/painel/invoice/:id' => 'sellers#view_invoice'
  get '/painel/entrega/:id' => 'sellers#view_delivery'
  get '/painel/entregar/:id' => 'sellers#deliver'
  get '/painel/entregado/:id' => 'sellers#delivered'
  get '/painel/cancelar/:id' => 'sellers#cancel'
  

  get '/admin' => 'admins#index'
  get '/admin/new' => 'admins#new'
  get '/admin/edit' => 'admins#edit'
  get '/admin/admins' => 'admins#admins'
  get '/admin/admins/apagar/:id' => 'admins#destroy_admin'
  get '/admin/clientes' => 'admins#users'
  get '/admin/clientes/:id' => 'admins#view_user'
  get '/admin/clientes/apagar/:id' => 'admins#destroy_user'
  get '/admin/vendedores' => 'admins#sellers'
  get '/admin/vendedores/:id' => 'admins#view_seller'
  get '/admin/pedidos' => 'admins#orders'
  get '/admin/pedidos/apagar/:id' => 'admins#destroy_order'
  get '/pedidos' => 'pages#orders'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HomeGás Services">
    <meta name="author" content="HomeGás">
    <link rel="icon" href="../../favicon.ico">
    <title>Dashboard</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/dashboard.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag("/assets/logo-homegas.png", :alt => "logo") %></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><%= current_admin.name %></a></li>
          <li><a href="/admins/sign_out">Sair</a></li>
        </ul>
      </div>
    </nav>
    <!-- Menu Left -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li style="
              padding: 20px 20px;
              font-size: 13px;
            "><%= current_admin.name %></li>
            <li><a href="/admin"><i class="glyphicon glyphicon-home pull-left"></i>Painel<span class="sr-only">(current)</span></a></li>
            <li><a href="/admin/vendedores"><i class="glyphicon glyphicon-tags"></i>Vendedores</a></li>
            <li><a href="/admin/clientes"><i class="glyphicon glyphicon-user pull-left"></i>Clientes</a></li>
            <li><a href="/admin/clientes"><i class="glyphicon glyphicon-list-alt pull-left"></i>Pedidos</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-usd glyphicon-wrench pull-left"></i>Financeiro</a></li>
            <li><a href="/admin/admins"><i class="glyphicon glyphicon-map-marker pull-left"></i>Admins</a></li>
            <li><a href="/admin/edit"><i class="glyphicon glyphicon-asterisk pull-left"></i>Alterar Dados</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= yield %>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
    $(function () {
    $('[data-tooltip="true"]').tooltip()
    })</script>
    <script src="/assets/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/assets/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/layouts/appbackup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'GasApp', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
  <% if user_signed_in? %>
  <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<%= yield %>

app/views/layouts/sellers.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HomeGás Services">
    <meta name="author" content="HomeGás">
    <link rel="icon" href="../../favicon.ico">
    <title>Dashboard</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700)">
    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/dashboard.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag("/assets/logo-homegas.png", :alt => "logo") %></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><%= current_seller.name %></a></li>
          <li><a href="/sellers/sign_out">Sair</a></li>
        </ul>
      </div>
    </nav>
    <!-- Menu Left -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li style="
              padding: 20px 20px;
              font-size: 13px;
            "><%= current_seller.firm %></li>
            <li><a href="/painel"><i class="glyphicon glyphicon-home pull-left"></i>Painel</a></li>
            <li><a href="/painel/pedidos"><i class="glyphicon glyphicon-list-alt"></i>Pedidos</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-map-marker pull-left"></i>Locais de Entrega</a></li>
            <li><a href="/painel/financeiro"><i class="glyphicon glyphicon-usd glyphicon-wrench pull-left"></i>Financeiro</a></li>
            <li><a href="/painel/dados"><i class="glyphicon glyphicon-asterisk pull-left"></i>Dados</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">  
          <%= yield %>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/assets/jquery.min.js"></script>
    <script src="/assets/site.js"></script>
    <script>$(function () {
    $('[data-tooltip="true"]').tooltip()
    })</script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>